[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
core_affinity = "0.8"
hashbrown = "0.16"
rtrb = "0.3"
tokio = { version = "1", features = ["rt", "net", "io-util", "time"] }
